In [4]:
import pandas as pd

In [5]:
# Get all the csv filepaths and create a list of files
bike_2020_01 = "Resources/JC-202001-citibike-tripdata.csv"
bike_2020_02 = "Resources/JC-202002-citibike-tripdata.csv"
bike_2020_03 = "Resources/JC-202003-citibike-tripdata.csv"
bike_2020_04 = "Resources/JC-202004-citibike-tripdata.csv"
bike_2020_05 = "Resources/JC-202005-citibike-tripdata.csv"
bike_2020_06 = "Resources/JC-202006-citibike-tripdata.csv"
bike_2020_07 = "Resources/JC-202007-citibike-tripdata.csv"
bike_2020_08 = "Resources/JC-202008-citibike-tripdata.csv"
bike_2020_09 = "Resources/JC-202009-citibike-tripdata.csv"
bike_2020_10 = "Resources/JC-202010-citibike-tripdata.csv"
bike_2020_11 = "Resources/JC-202011-citibike-tripdata.csv"
bike_2020_12 = "Resources/JC-202012-citibike-tripdata.csv"

data = [bike_2020_01,bike_2020_02,bike_2020_03,bike_2020_04,bike_2020_05,bike_2020_06,bike_2020_07, bike_2020_08,bike_2020_09,bike_2020_10,bike_2020_11,bike_2020_12]

In [11]:
#Create a dataframe for the whole year
bike_list = []

for file in data:
    bike_list.append(pd.read_csv(file))

bike_2020 = pd.concat(bike_list, sort=False)
bike_2020

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11689,1750,2020-12-31 23:07:44.0030,2020-12-31 23:36:54.4710,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,40440,Customer,1969,0
11690,1519,2020-12-31 23:18:00.2630,2020-12-31 23:43:19.8590,3184,Paulus Hook,40.714145,-74.033552,3195,Sip Ave,40.730897,-74.063913,46340,Customer,1969,0
11691,1761,2020-12-31 23:31:09.4620,2021-01-01 00:00:31.3290,3195,Sip Ave,40.730897,-74.063913,3270,Jersey & 6th St,40.725289,-74.045572,40907,Customer,1998,1
11692,637,2020-12-31 23:35:45.4640,2020-12-31 23:46:22.7300,3681,Grand St,40.715178,-74.037683,3199,Newport Pkwy,40.728745,-74.032108,42250,Customer,1969,0
11693,1607,2020-12-31 23:48:34.5750,2021-01-01 00:15:22.3090,3267,Morris Canal,40.712419,-74.038526,3267,Morris Canal,40.712419,-74.038526,48742,Subscriber,1982,1

In [12]:
# Data types
bike_2020.dtypes

tripduration                 int64
starttime                   object
stoptime                    object
start station id             int64
start station name          object
start station latitude     float64
start station longitude    float64
end station id               int64
end station name            object
end station latitude       float64
end station longitude      float64
bikeid                       int64
usertype                    object
birth year                   int64
gender                       int64
dtype: object

In [13]:
# Drop age > 100 years old 
clean_data = bikedata_2020.loc[bikedata_2020["birth year"] > 1920, :]

# reset index
clean_data = clean_data.reset_index(drop = True)

In [14]:
clean_data

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336776,1750,2020-12-31 23:07:44.0030,2020-12-31 23:36:54.4710,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,40440,Customer,1969,0
336777,1519,2020-12-31 23:18:00.2630,2020-12-31 23:43:19.8590,3184,Paulus Hook,40.714145,-74.033552,3195,Sip Ave,40.730897,-74.063913,46340,Customer,1969,0
336778,1761,2020-12-31 23:31:09.4620,2021-01-01 00:00:31.3290,3195,Sip Ave,40.730897,-74.063913,3270,Jersey & 6th St,40.725289,-74.045572,40907,Customer,1998,1
336779,637,2020-12-31 23:35:45.4640,2020-12-31 23:46:22.7300,3681,Grand St,40.715178,-74.037683,3199,Newport Pkwy,40.728745,-74.032108,42250,Customer,1969,0
336780,1607,2020-12-31 23:48:34.5750,2021-01-01 00:15:22.3090,3267,Morris Canal,40.712419,-74.038526,3267,Morris Canal,40.712419,-74.038526,48742,Subscriber,1982,1

In [15]:
clean_data.describe()

,tripduration,start station id,start station latitude,start station longitude,end station id,end station latitude,end station longitude,bikeid,birth year,gender
count,3.367810e+05,336781.000000,336781.000000,336781.000000,336781.000000,336781.000000,336781.000000,336781.000000,336781.000000,336781.000000
mean,1.574787e+03,3304.141659,40.722216,-74.046752,3302.785721,40.721736,-74.045932,40638.324050,1981.304809,1.096855
std,1.802533e+04,184.601482,0.007351,0.011905,190.111644,0.099507,0.180834,6069.107262,11.023759,0.630353
min,6.100000e+01,3184.000000,40.709651,-74.083639,82.000000,0.000000,-74.083639,14531.000000,1930.000000,0.000000
25%,3.260000e+02,3195.000000,40.716870,-74.051789,3195.000000,40.716870,-74.050656,42141.000000,1969.000000,1.000000
50%,6.150000e+02,3209.000000,40.721124,-74.043991,3209.000000,40.721124,-74.043845,42373.000000,1984.000000,1.000000
75%,1.416000e+03,3276.000000,40.727224,-74.037683,3276.000000,40.727224,-74.037683,43543.000000,1990.000000,2.000000
max,3.261756e+06,3792.000000,40.748716,-74.032108,4071.000000,40.848282,0.000000,49734.000000,2004.000000,2.000000

In [18]:
# Replace gender
# (Zero=unknown; 1=male; 2=female)

In [16]:
# Export clean_data to a CSV file 

#clean_data.to_csv("Resources/bikedata_2020.csv", index=False)